<Project>
  <PropertyGroup Label="C#">
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup Label="Code Analysis">
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" PrivateAssets="All" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)analysis\banned-symbols.txt" />
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory)analysis\gamekit.globalconfig" />
  </ItemGroup>
  <PropertyGroup Label="Code Analysis">
    <AnalysisMode>Default</AnalysisMode>
    <AnalysisModeDesign>Default</AnalysisModeDesign>
    <AnalysisModeDocumentation>Recommended</AnalysisModeDocumentation>
    <AnalysisModeGlobalization>Recommended</AnalysisModeGlobalization>
    <AnalysisModeInteroperability>Recommended</AnalysisModeInteroperability>
    <AnalysisModeMaintainability>Recommended</AnalysisModeMaintainability>
    <AnalysisModeNaming>Default</AnalysisModeNaming>
    <AnalysisModePerformance>Minimum</AnalysisModePerformance>
    <AnalysisModeReliability>Recommended</AnalysisModeReliability>
    <AnalysisModeSecurity>Default</AnalysisModeSecurity>
    <AnalysisModeUsage>Default</AnalysisModeUsage>
  </PropertyGroup>
</Project>
